version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"