version: '3'

services:
  mysql:
    image: mysql:8.0.25
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"